name: Trigger auto deployment for containerappjornadatest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerappjornadatest-AutoDeployTrigger-a18c6b00-1b9d-4999-8e7d-5f8268373f3d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJORNADATEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJORNADATEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJORNADATEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acraksdevu75.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPJORNADATEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJORNADATEST_REGISTRY_PASSWORD }}
          containerAppName: containerappjornadatest
          resourceGroup: rg-aks-dev
          imageToBuild: acraksdevu75.azurecr.io/containerappjornadatest:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


